title: Who's That Cop
# email: your-email@example.com
description: >- 
  Look up LAPD officers. Inspired by @whosthatcop on Twitter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: exmember
github_username: exmember

plugins:
  - jekyll-autoprefixer
  - jekyll-remote-theme

remote_theme: 18F/uswds-jekyll
