name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # Get Ubuntu version, we need it for the bundler cache
      # see https://github.com/actions/cache/issues/543
      - run: |
          echo "OS_VERSION=`lsb_release -sr`" >> $GITHUB_ENV
      - name: 📂 setup
        uses: actions/checkout@v2
        # for jekyll-last-modified-at, may be very slow for large repositories!
        # with:
          # fetch-depth: '0'
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          key: ${{ runner.os }}${{ env.OS_VERSION }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}${{ env.OS_VERSION }}-gems-
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
